# Generated by Django 3.0.6 on 2020-05-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('ContactPerson', models.CharField(help_text='First Contact', max_length=100)),
                ('Status', models.CharField(choices=[('Lead', 'Lead'), ('Deal', 'Deal'), ('CLient', 'Client')], default='Lead', help_text='Current Status', max_length=10)),
                ('Phone', models.CharField(blank=True, max_length=30, null=True)),
                ('Mobile', models.CharField(max_length=30, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('GPSLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Designation', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Contractor', 'Contractor')], default='Permanent', max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(max_length=30)),
                ('Address', models.TextField()),
                ('CostPerHour', models.FloatField()),
                ('Remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvNumber', models.CharField(help_text='Enter SO Number if Invoice not created and change later', max_length=20)),
                ('JobType', models.CharField(choices=[('Installation', 'Installation'), ('AfterSales', 'AfterSales')], default='Installation', max_length=15)),
                ('Status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Differed', 'Differed'), ('In Progress', 'In Progress')], default='In Progress', max_length=15)),
                ('Date', models.DateField()),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('CustomerName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aft.Customers')),
            ],
            options={
                'verbose_name_plural': 'Job',
                'unique_together': {('InvNumber', 'JobType')},
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('Phone', models.CharField(blank=True, max_length=30, null=True)),
                ('Mobile', models.CharField(max_length=30, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('WebAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('GPSLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('DueDate', models.DateTimeField()),
                ('Priority', models.CharField(choices=[('Highest', 'Highest'), ('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low'), ('Lowest', 'Lowest')], default='High', max_length=10)),
                ('Status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Differed', 'Differed'), ('In Progress', 'In Progress')], default='In Progress', max_length=15)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('CustomerName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aft.Customers')),
                ('EmployeeName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aft.Employees')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='JobTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('WorkHrs', models.FloatField()),
                ('LabourCost', models.FloatField()),
                ('Remarks', models.CharField(max_length=100)),
                ('EmployeeName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aft.Employees')),
                ('InvNumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aft.Jobs')),
            ],
            options={
                'verbose_name_plural': 'JobTime',
            },
        ),
        migrations.CreateModel(
            name='JobMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Material', models.CharField(max_length=100)),
                ('Quantity', models.FloatField()),
                ('UnitCostwithGST', models.FloatField()),
                ('Remarks', models.CharField(max_length=100)),
                ('InvNumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aft.Jobs')),
                ('Suppliers', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aft.Suppliers')),
            ],
            options={
                'verbose_name_plural': 'JobMaterial',
            },
        ),
    ]
